name: fits
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase core & auth
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0

  # Firestore (para persistir perfiles de usuario)
  cloud_firestore: ^5.0.0

  # Google Sign-In
  google_sign_in: ^6.2.1

  # Facebook Auth
  flutter_facebook_auth: ^6.1.1

  # State management
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Activa tus assets (descomenta y pon tus imágenes si las usas)
  # assets:
  #   - images/