name: fits
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase core & auth
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0

  # Firestore (para persistir perfiles de usuario)
  cloud_firestore: ^5.0.0

  # Google Sign-In
  google_sign_in: ^6.2.1

  # Facebook Auth
  flutter_facebook_auth: ^6.1.1

  # State management
  provider: ^6.0.0

  # Para fechas en español y formateo de días
  intl: ^0.20.2

  # Generador de identificadores únicos (para modelos con id)
  uuid: ^4.3.3

  # Indicador de porcentaje circular
  percent_indicator: ^4.2.3

  # Almacenamiento local para notas y tareas
  shared_preferences: ^2.2.2

  # Criptografía para notas seguras
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/core/utils/images/
    - assets/exercises.json
    - assets/exercises/Dumbbell_Flyes/
    - assets/exercises/Dumbbell_Lunges/
    - assets/exercises/Dumbbell_Step_Ups/
    - assets/exercises/Freehand_Jump_Squat/
    - assets/exercises/Lying_Close-Grip_Bar_Curl_On_High_Pulley/
    - assets/exercises/Lying_Dumbbell_Tricep_Extension/
    - assets/exercises/Lying_Leg_Curls/
    - assets/exercises/Lying_T-Bar_Row/
    - assets/exercises/Machine_Bench_Press/
    - assets/exercises/Machine_Bicep_Curl/
    - assets/exercises/Medicine_Ball_Chest_Pass/
    - assets/exercises/Mixed_Grip_Chin/
    - assets/exercises/Mountain_Climbers/
    - assets/exercises/Muscle_Up/
    - assets/exercises/Narrow_Stance_Squats/
    - assets/exercises/One-Arm_Dumbbell_Row/
    - assets/exercises/One-Arm_Kettlebell_Row/
    - assets/exercises/One_Arm_Dumbbell_Bench_Press/
    - assets/exercises/One_Arm_Dumbbell_Preacher_Curl/
    - assets/exercises/One_Arm_Lat_Pulldown/
    - assets/exercises/Otis-Up/
    - assets/exercises/Plank/
    - assets/exercises/Plyo_Push-up/
    - assets/exercises/Preacher_Curl/
    - assets/exercises/Pullups/
    - assets/exercises/Push-Ups_With_Feet_Elevated/
    - assets/exercises/Pushups/
    - assets/exercises/Pushups_Close_and_Wide_Hand_Positions/
    - assets/exercises/Push_Up_to_Side_Plank/
    - assets/exercises/Reverse_Crunch/
    - assets/exercises/Reverse_Grip_Bent-Over_Rows/
    - assets/exercises/Reverse_Grip_Triceps_Pushdown/
    - assets/exercises/Rocky_Pull-Ups_Pulldowns/
    - assets/exercises/Romanian_Deadlift/
    - assets/exercises/Rope_Crunch/
    - assets/exercises/Rope_Straight-Arm_Pulldown/
    - assets/exercises/Russian_Twist/
    - assets/exercises/Scissor_Kick/
    - assets/exercises/Seated_Cable_Rows/
    - assets/exercises/Seated_Dumbbell_Curl/
    - assets/exercises/Seated_Flat_Bench_Leg_Pull-In/
    - assets/exercises/Seated_Leg_Curl/
    - assets/exercises/Seated_Triceps_Press/
    - assets/exercises/Shotgun_Row/
    - assets/exercises/Side_Jackknife/
    - assets/exercises/Single_Leg_Glute_Bridge/
    - assets/exercises/Sit-Up/
    - assets/exercises/Sled_Push/
    - assets/exercises/Smith_Machine_Bench_Press/
    - assets/exercises/Smith_Machine_Bent_Over_Row/
    - assets/exercises/Smith_Machine_Decline_Press/
    - assets/exercises/Smith_Machine_Leg_Press/
    - assets/exercises/Smith_Machine_Squat/
    - assets/exercises/Snatch_Balance/
    - assets/exercises/Spider_Crawl/
    - assets/exercises/Split_Squat_with_Dumbbells/
    - assets/exercises/Standing_Biceps_Cable_Curl/
    - assets/exercises/Standing_Cable_Chest_Press/
    - assets/exercises/Standing_Calf_Raises/
    - assets/exercises/Standing_Dumbbell_Reverse_Curl/
    - assets/exercises/Standing_One-Arm_Cable_Curl/
    - assets/exercises/Standing_Rope_Crunch/