name: fits
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase core & auth
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0

  # Firestore (para persistir perfiles de usuario)
  cloud_firestore: ^5.0.0

  # Google Sign-In
  google_sign_in: ^6.2.1

  # Facebook Auth
  flutter_facebook_auth: ^6.1.1

  # State management
  provider: ^6.0.0

  # Para fechas en español y formateo de días
  intl: ^0.18.0

  # Generador de identificadores únicos (para modelos con id)
  uuid: ^4.3.3

  # Para llamadas HTTP (necesario para la integración con Open Food Facts y WGER)
  http: ^1.2.1

  # Animations
  flutter_animate: ^4.5.0

  # Safe area and screen utils (opcional, recomendados para layouts modernos)
  flutter_screenutil: ^5.9.0

  # Circular percent indicators para barras de macros
  percent_indicator: ^4.2.3

  # HTML parser (para limpiar descripciones HTML de WGER)
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/exercise/
    - assets/exercises.json